### ISSUE TITLE
WebkitForWayland doesn't emulate mouse events from touch events

### ISSUE THREAD

**Issue by JPEWdev** [WebKitForWayland/webkit#22]
WebkitForWayland does not appear to emulate the mouse events when using a touch screen as most other browsers do. This can be tested using this test page:

http://unixpapa.com/js/testmouse-2.html

**Comment by zdobersek** [comment]
Should be fixed with https://github.com/WebKitForWayland/webkit/commit/5b89d0941e304747b3e6e092578d346693f9dbb1.
The touch events that are not handled are now translated into corresponding pointer events, with the first touch point serving as the basis for the position and type of the event.
