### ISSUE TITLE
WPE fails to build on the RPI platform due to -std=c99 flag

### ISSUE THREAD

**Issue by clopez** [WebKitForWayland/webkit#27]
Trying to build WebKitForWayland (tag wpe-20160616) with Yocto/OE I get the following error:

    make[2]: Entering directory '/home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/build'
    [ 21%] Building C object Source/ThirdParty/WPE/CMakeFiles/WPE.dir/src/renderer.c.o
    cd /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/build/Source/ThirdParty/WPE && /home/clopez/yocto-rpi-wayland/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc  -DBUILDING_WITH_CMAKE=1 -DBUILDING_WPE__=1 -DDATA_DIR=\"/usr/share\" -DHAVE_CONFIG_H=1 -DWPE_EXPORTS -I/home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/include -I/home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src  -march=armv7-a -marm -mfpu=neon-vfpv4  -mfloat-abi=hard -mtune=cortex-a7  --sysroot=/home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0=/usr/src/debug/webkitforwayland/wpe-20160616-r0 -fdebug-prefix-map=/home/clopez/yocto-rpi-wayland/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3=  -std=c99 -DNDEBUG -fno-exceptions -fno-strict-aliasing -fvisibility=hidden -fPIC   -o CMakeFiles/WPE.dir/src/renderer.c.o   -c /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src/renderer.c
    In file included from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/vcos.h:118:0,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vmcs_host/vc_dispmanx.h:33,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/EGL/eglplatform.h:110,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/include/wpe/renderer-backend-egl.h:38,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src/renderer.c:27:
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h:131:20: error: field 'expires' has incomplete type
        struct timespec expires;               /**< absolute time of next expiration, or 0 if disarmed*/
                        ^
    In file included from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/vcos.h:118:0,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vmcs_host/vc_dispmanx.h:33,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/EGL/eglplatform.h:110,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/include/wpe/renderer-backend-egl.h:38,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src/renderer.c:27:
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h: In function 'vcos_semaphore_wait_timeout':
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h:295:20: error: storage size of 'ts' isn't known
        struct timespec ts;
                        ^
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h:297:22: error: 'CLOCK_REALTIME' undeclared (first use in this function)
        if (clock_gettime(CLOCK_REALTIME, &ts) == -1)
                          ^
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h:297:22: note: each undeclared identifier is reported only once for each function it appears in
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h: In function 'vcos_sleep':
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/pthreads/vcos_platform.h:382:20: error: storage size of 'ts' isn't known
        struct timespec ts;
                        ^
    In file included from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/vcos.h:140:0,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vmcs_host/vc_dispmanx.h:33,
                     from /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/EGL/eglplatform.h:110,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/include/wpe/renderer-backend-egl.h:38,
                     from /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src/renderer.c:27:
    /home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/webkit-wpe-20160616/Source/ThirdParty/WPE/src/renderer.c: At top level:
    /home/clopez/yocto-rpi-wayland/tmp/sysroots/raspberrypi3/usr/include/interface/vcos/vcos_mem.h:93:15: warning: inline function 'vcos_get_free_mem' declared but never defined
     unsigned long vcos_get_free_mem(void);
                   ^
    Source/ThirdParty/WPE/CMakeFiles/WPE.dir/build.make:185: recipe for target 'Source/ThirdParty/WPE/CMakeFiles/WPE.dir/src/renderer.c.o' failed
    make[2]: *** [Source/ThirdParty/WPE/CMakeFiles/WPE.dir/src/renderer.c.o] Error 1
    make[2]: Leaving directory '/home/clopez/yocto-rpi-wayland/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/webkitforwayland/wpe-20160616-r0/build'
    CMakeFiles/Makefile2:976: recipe for target 'Source/ThirdParty/WPE/CMakeFiles/WPE.dir/all' failed

According to http://stackoverflow.com/questions/14415465/why-do-i-get-in-my-timespec-array-the-error-array-type-has-incomplete-element-t this is triggered because the usage of the  cflag -std=c99.

**Comment by clopez** [comment]
Removing the line that sets the flag -std=c99 from Source/ThirdParty/WPE/CMakeLists.txt fixes the issue. I can submit a PR if you think this is the appropriate fix.

**Comment by zdobersek** [comment]
Does defining _GNU_SOURCE at the top of renderer.c help?

**Comment by clopez** [comment]
Yes. That fixes the build also.

**Comment by zdobersek** [comment]
I committed c7e74ec98c77dcd50a39a52804651a8ddd55706f which defines _POSIX_SOURCE via compilation flags.

I don't think it's the proper solution -- the specific build failure is due to the platform-specific headers not defining the proper macro on their own.
