### ISSUE TITLE
WPE 20160804 fails to build on OdroidXU4 (Exynos5422) 

### ISSUE THREAD

**Issue by mihailescu2m** [WebKitForWayland/webkit#32]
because of 2 issues:

* glib fails to compile with the error:
`gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]`
this can be fixed either as discussed in https://dev.openwrt.org/ticket/22193 or by setting format-nonliteral as a warning instead of error in the jhbuild flags

* WebCore link error: libWPE.so.0.0.20160804 needs to be linked agains -ldl
(i fixed this for my build by manually editing link.txt and adding -ldl)

**Comment by zdobersek** [comment]
GLib build error is out of the scope of this project.

libWPE.so link error should be fixed with 9e82440247d4c84685268b0f2ea7d8e070f44dad.

Feel free to reopen if the latter issue persists.
